{% set name = "htmlark" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/HTMLArk-{{ version }}.tar.gz
  sha256: 1b19599371e30c04383c4aff2837ac326be689a6868e2867efb0414c2ddfe261

build:
  entry_points:
    - htmlark = htmlark:_main_wrapper
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - beautifulsoup4

test:
  imports:
    - htmlark
  commands:
    - pip check
    - htmlark --help
  requires:
    - pip

about:
  home: https://github.com/BitLooter/htmlark
  summary: Pack a webpage including support files into a single HTML file.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - druvus
